//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_entityframework_okul2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public long kayit_no { get; set; }
        public int og_no { get; set; }
        public byte ders_no { get; set; }
        public Nullable<byte> yaz1 { get; set; }
        public Nullable<byte> yaz2 { get; set; }
        public Nullable<byte> soz { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
