//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_entityframework_okul2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Notlar = new HashSet<Notlar>();
        }
        [Required(ErrorMessage = "Alan boþ olamaz.")]
        public int og_no { get; set; }
        [Required(ErrorMessage = "Alan boþ olamaz.")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter olabilir.")]
        public string og_ad_soyad { get; set; }
        [Required(ErrorMessage = "Alan boþ olamaz.")]
        public System.DateTime dog_tar { get; set; }
        [Required(ErrorMessage = "Alan boþ olamaz.")]
        public long tc_kimlik { get; set; }
        public string adres { get; set; }
        [Required(ErrorMessage = "Alan boþ olamaz.")]
        [EmailAddress(ErrorMessage ="Lütfen geçerli bir e-mail adresi giriniz.")]
        public string email { get; set; }
        [Required(ErrorMessage = "Sýnýf seçmek zorunlu.")]
        public string sinif_adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlar { get; set; }
        public virtual siniflar siniflar { get; set; }
    }
}
